### PR TITLE
updating my caption

### LINKED ISSUE #3: Add A New Slide
## We Need More Slides
Grab another octocat and create a new slide from scratch.
If you need help, check out the Appendix in the training manual.

### PR DESCRIPTION
**Pull request by ccjoshk**
Adding caption to my file. Resolves #3

### CODE REVIEW

**Comment by jzantony** [comment]
reviewd

**Review by brittaneyross — COMMENTED** [review]
looks good

**Review by brittaneyross — APPROVED** [review]
looks good

**Comment by atipchao** [comment]
I also delete the "add-caption-ccjoshk branch"

**Pull request merged**
